# Decldir specific substitutions

[subs]

# if to disable the homedir ("~") special substitutions
# set true for safety, and use "{HOME}" for homedir
disable_homedir_subs = false

# global substitutions applied for most strings in toml files
# subs list example:
# "foo" = "bar"
[[global]]

# specific substitutions for filepaths & commands
[[paths_cmds]]
